use leptos::*;
use leptos_router::*;

use crate::api::ApiClient;
use crate::components::loading::Loading;
use crate::components::{Alert, AlertVariant, Button, ButtonVariant};
use crate::i18n::use_i18n;
use crate::utils::copy_to_clipboard;

/// How long the copy button flashes its "copied" label, in milliseconds.
const COPIED_FLASH_MS: u32 = 2000;

/// Read-only daily task report.
///
/// The report body is generated by the backend and is rendered verbatim as a text
/// node inside a preformatted block — never as HTML, so task titles written by other
/// household members cannot inject markup. The page holds the report in memory only
/// and offers exactly one action: copy to clipboard.
#[component]
pub fn ReportPage() -> impl IntoView {
    let i18n = use_i18n();
    let i18n_stored = store_value(i18n);

    let params = use_params_map();
    let household_id = move || params.with(|p| p.get("id").cloned().unwrap_or_default());

    let report_text = create_rw_signal(String::new());
    let loading = create_rw_signal(true);
    let error = create_rw_signal(Option::<String>::None);
    let copied = create_rw_signal(false);

    create_effect(move |_| {
        let id = household_id();
        if id.is_empty() {
            return;
        }

        wasm_bindgen_futures::spawn_local(async move {
            match ApiClient::get_daily_report(&id).await {
                Ok(text) => report_text.set(text),
                Err(e) => error.set(Some(e)),
            }
            loading.set(false);
        });
    });

    let copy_report = move |_| {
        let text = report_text.get_untracked();
        if text.is_empty() {
            return;
        }

        wasm_bindgen_futures::spawn_local(async move {
            match copy_to_clipboard(&text).await {
                Ok(()) => {
                    copied.set(true);
                    gloo_timers::future::TimeoutFuture::new(COPIED_FLASH_MS).await;
                    copied.set(false);
                }
                Err(e) => error.set(Some(e)),
            }
        });
    };

    let copy_disabled = Signal::derive(move || loading.get() || report_text.get().is_empty());

    view! {
        <div class="report-page">
            <div class="report-actions">
                <Button
                    variant=ButtonVariant::Secondary
                    disabled=copy_disabled
                    on_click=Callback::new(copy_report)
                >
                    {move || {
                        if copied.get() {
                            i18n_stored.get_value().t("report.copied")
                        } else {
                            i18n_stored.get_value().t("report.copy_button")
                        }
                    }}
                </Button>
            </div>

            <Show when=move || loading.get() fallback=|| ()>
                <Loading />
            </Show>

            {move || error.get().map(|_| view! {
                <Alert variant=AlertVariant::Error>
                    {i18n_stored.get_value().t("report.load_error")}
                </Alert>
            })}

            <pre class="report-text">{move || report_text.get()}</pre>
        </div>
    }
}
